// Models for Law Proposals feature
// Based on backend API specification

/**
 * Député (Deputy) - Author or co-signatory
 */
export interface Depute {
  nom: string;
  groupePolitique: string;
  groupePolitiqueCode: string;
  photoUrl: string | null;
  urlDepute: string | null;
}

/**
 * Simplified section of the exposé des motifs
 */
export interface SimplifiedExposeMotif {
  ordre: number;
  titre: string;
  texte: string;
}

/**
 * Simplified article resume
 */
export interface SimplifiedArticle {
  ordre: number;
  numero: string;
  resume: string;
}

/**
 * Simplified version of a law proposal (generated by AI)
 */
export interface SimplifiedVersion {
  status: 'completed' | 'pending' | 'failed';
  generatedAt?: string;
  keyPoints: string[];
  exposeMotifs?: SimplifiedExposeMotif[];
  articles?: SimplifiedArticle[];
}

/**
 * Official article (full legal text)
 */
export interface Article {
  numero: string;
  titre: string | null;
  texte: string;
}

/**
 * Official section (full legal text)
 */
export interface Section {
  type: 'expose_motifs' | 'articles' | 'sommaire' | 'autre';
  titre: string;
  texte: string;
  articles: Article[];
}

/**
 * Amendement (amendment)
 */
export interface Amendement {
  numero: string;
  date: string;
  auteur: string | null;
  statut: string | null;
  url: string | null;
}

/**
 * Law Proposal - Full version (for detail page)
 */
export interface LawProposal {
  numero: string;
  titre: string;
  typeProposition: 'ordinaire' | 'constitutionnelle';
  legislature: string;
  dateMiseEnLigne: string;
  dateDepot: string | null;
  description: string | null;
  urlDocument: string;
  urlDossierLegislatif: string | null;

  auteur: Depute;
  coSignataires: Depute[];

  simplified?: SimplifiedVersion;

  sections: Section[];
  amendements: Amendement[];
}

/**
 * Law Proposal Summary - For listing page
 */
export interface LawProposalSummary {
  numero: string;
  titre: string;
  typeProposition: 'ordinaire' | 'constitutionnelle';
  dateMiseEnLigne: string;
  dateDepot: string | null;

  auteur: Depute;
  coSignatairesCount: number;

  simplified?: {
    status: 'completed' | 'pending' | 'failed';
    keyPoints: string[];
  };
}

/**
 * Pagination metadata
 */
export interface Pagination {
  page: number;
  limit: number;
  total: number;
  totalPages: number;
  hasNextPage: boolean;
  hasPreviousPage: boolean;
}

/**
 * API Response for law proposals listing
 */
export interface LawProposalsListResponse {
  data: LawProposalSummary[];
  pagination: Pagination;
}

/**
 * Query parameters for listing endpoint
 */
export interface LawProposalsQueryParams {
  page?: number;
  limit?: number;
  sort?: string;
  groupePolitique?: string;
  typeProposition?: 'ordinaire' | 'constitutionnelle';
  dateDebut?: string;
  dateFin?: string;
  simplificationStatus?: 'completed' | 'pending' | 'failed';
}

/**
 * Political group codes mapping
 */
export const POLITICAL_GROUPS: Record<string, { name: string; color: string }> = {
  RN: { name: 'Rassemblement National', color: '#3d6a8a' },
  LFI_NFP: { name: 'La France insoumise - Nouveau Front Populaire', color: '#9e4a5a' },
  SOC: { name: 'Socialistes et apparentés', color: '#b87070' },
  ECO: { name: 'Écologiste et Social', color: '#4a9a4a' },
  GDR: { name: 'Gauche Démocrate et Républicaine', color: '#a84040' },
  EPR: { name: 'Ensemble pour la République', color: '#b8a020' },
  DEM: { name: 'Les Démocrates', color: '#c87820' },
  HOR: { name: 'Horizons et apparentés', color: '#3090b0' },
  DR: { name: 'Droite Républicaine', color: '#4a7ab0' },
  UDR: { name: 'Union des droites pour la République', color: '#2a4a6a' },
  NI: { name: 'Non inscrit', color: '#707070' },
  UNKNOWN: { name: 'Non spécifié', color: '#909090' },
};

export type PoliticalGroupCode = keyof typeof POLITICAL_GROUPS;
